// ============================================================================
// AUTO-GENERATED by gen_tb_config.py — do not edit manually
// Layer: 5 x 16, Degree=3
// ============================================================================
localparam integer NUM_INPUTS     = 5;
localparam integer NUM_OUTPUTS    = 16;
localparam integer DEGREE         = 3;
localparam integer ACC_WIDTH      = 22;
localparam integer REQUANT_SHIFT  = 5;
localparam string  TESTCASE_DIR   = "testcase_data/layer_0_5x16";
localparam string  MIF_PREFIX     = "testcase_data/layer_0_5x16/mem_init/weights_pe_";
