// Auto-generated by generate_testcase.py
// Testcase: 64 x 64, Degree=3, Seed=42
localparam integer NUM_INPUTS     = 64;
localparam integer NUM_OUTPUTS    = 64;
localparam integer DEGREE         = 3;
localparam integer ACC_WIDTH      = 22;
localparam integer REQUANT_SHIFT  = 5;
localparam string  TESTCASE_DIR   = "testcase_64x64";
localparam string  MIF_PREFIX     = "testcase_64x64/mem_init/weights_pe_";
