#!/usr/bin/env python3
"""
Generate tb_config.svh for a specific Chebyshev KAN layer.

Usage:
    python gen_tb_config.py --num_inputs 5 --num_outputs 16 --testcase_dir testcase_data/layer_0_5x16
    python gen_tb_config.py --num_inputs 16 --num_outputs 1 --testcase_dir testcase_data/layer_1_16x1

This writes tb_config.svh to the current directory (or --output_dir).
The generated file is `included by tb_layer.sv.
"""

import argparse
import os

def generate_config(
    num_inputs: int,
    num_outputs: int,
    testcase_dir: str,
    degree: int = 3,
    acc_width: int = 22,
    requant_shift: int = 14,
    output_dir: str = ".",
):
    mif_prefix = f"{testcase_dir}/mem_init/weights_pe_"

    content = f"""\
// ============================================================================
// AUTO-GENERATED by gen_tb_config.py — do not edit manually
// Layer: {num_inputs} x {num_outputs}, Degree={degree}
// ============================================================================
localparam integer NUM_INPUTS     = {num_inputs};
localparam integer NUM_OUTPUTS    = {num_outputs};
localparam integer DEGREE         = {degree};
localparam integer ACC_WIDTH      = {acc_width};
localparam integer REQUANT_SHIFT  = {requant_shift};
localparam string  TESTCASE_DIR   = "{testcase_dir}";
localparam string  MIF_PREFIX     = "{mif_prefix}";
"""

    out_path = os.path.join(output_dir, "tb_config.svh")
    with open(out_path, "w") as f:
        f.write(content)
    print(f"Wrote {out_path}")
    print(f"  NUM_INPUTS  = {num_inputs}")
    print(f"  NUM_OUTPUTS = {num_outputs}")
    print(f"  DEGREE      = {degree}")
    print(f"  REQUANT_SHIFT = {requant_shift}")
    print(f"  TESTCASE_DIR  = {testcase_dir}")
    print(f"  MIF_PREFIX    = {mif_prefix}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate tb_config.svh for Chebyshev layer testbench")
    parser.add_argument("--num_inputs",    type=int, required=True, help="Number of input channels")
    parser.add_argument("--num_outputs",   type=int, required=True, help="Number of output channels (PEs)")
    parser.add_argument("--testcase_dir",  type=str, required=True, help="Path to testcase directory")
    parser.add_argument("--degree",        type=int, default=3,     help="Chebyshev polynomial degree (default: 3)")
    parser.add_argument("--acc_width",     type=int, default=22,    help="Accumulator width (default: 22)")
    parser.add_argument("--requant_shift", type=int, default=5,     help="Requant right-shift (default: 5)")
    parser.add_argument("--output_dir",    type=str, default=".",   help="Where to write tb_config.svh")
    args = parser.parse_args()

    generate_config(
        num_inputs=args.num_inputs,
        num_outputs=args.num_outputs,
        testcase_dir=args.testcase_dir,
        degree=args.degree,
        acc_width=args.acc_width,
        requant_shift=args.requant_shift,
        output_dir=args.output_dir,
    )
