// ============================================================================
// AUTO-GENERATED by gen_tb_config.py — do not edit manually
// Layer: 16 x 1, Degree=3
// ============================================================================
localparam integer NUM_INPUTS     = 16;
localparam integer NUM_OUTPUTS    = 1;
localparam integer DEGREE         = 3;
localparam integer ACC_WIDTH      = 22;
localparam integer REQUANT_SHIFT  = 5;
localparam string  TESTCASE_DIR   = "airfoil_results/layer_1_16x1";
localparam string  MIF_PREFIX     = "airfoil_results/layer_1_16x1/mem_init/weights_pe_";
